### ISSUE TITLE
wifi-reset.sh: command not found

### ISSUE THREAD

**Issue by thebobbyboy420** [aprepo/osx-wifi-keepalive#1]
please help me.

i have downloaded both files placed them into my downloads dir

i run the script wifi-keepalive.sh but i have a problem, how do i fix this?

```
homes-iMac:~ home$ /Users/home/Downloads/osx-wifi-keepalive-master/wifi-keepalive.sh 
.................................................................................................2017-05-09-10:03:18 : Connection DOWN, reseting wifi...
/Users/home/Downloads/osx-wifi-keepalive-master/wifi-keepalive.sh: line 13: wifi-reset.sh: command not found
```

**Comment by aprepo** [comment]
@elogicuk check the latest version. The old version worked only if the script was in path. I have local dir in path so it wasn't a problem for me... Now it resolves the path of the script first and assumes the other script is in same directory.
